baseURL: http://example.org/
languageCode: en-us
title: Qcloud's Blog
theme: "PaperMod"

menu:
    main:
        - name: Archive
          url: archives
          weight: 5
        
        - name: Home
          url:
          weight: 5
          
params:
    homeInfoParams:
        Title: Qcloud's Blog
        Content: >
            Welcome to my blog!

            - Hi there.

            - This is qcloud.

            - Testing to build a blog.

    socialIcons:
        - name: github
          url: "https://github.com/qcloudq"


